name: WakaTime Readme Stats

on:
  schedule:
    # Runs at 12:00 AM UTC daily
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anmol098/waka-readme-stats@v1 
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Customize what you display (optional)
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_TOTAL_CODE_TIME: "False" # Setting this to "False" hides the total time, similar to your initial request preference.
          SHOW_COMMIT: "False"
          COMMIT_BY_OWNER: "True" # Commit the update as the repo owner
